language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

before_script:
  - python ./setup.py install
  - pip install -r requirements-test.txt
  - pip install -r doc/doc_requirements.txt
script:
  - py.test .
  # Code quality check
  - flake8 spinn_machine unittests
  - cd doc/source && sphinx-build -T -E -b readthedocsdirhtml -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - cd doc/source && sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - cd doc/source && sphinx-build -T -b readthedocssinglehtmllocalmedia -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia
