language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

install:
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNUtils.git@master
  - python ./setup.py install
before_script:
  - pip install -r requirements-test.txt
script:
  - py.test .
  # Code quality check
  - flake8 spinn_machine unittests
