language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

install:
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNUtils.git@master
  - python ./setup.py install
before_script:
  - pip install -r requirements-test.txt
  - pip install -r doc/doc_requirements.txt
script:
  - py.test .
  # Code quality check
  - flake8 spinn_machine unittests
  - cd doc/source
  - sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia
